export const serialNumberTable = {
    1: 'Using Unirep Social',
    1_1: 'Getting Started',
    1_1_1: 'Signing Up',
    1_1_2: 'Generating A Private Key',
    1_1_3: 'Storing Your Private Key',
    1_2: 'The Platform, Pages, and Features',
    1_2_1: 'Platform',
    1_2_2: 'Pages',
    2: 'Managing Your Account',
    2_1: 'Manage account 2nd',
    2_1_1: 'Manage account 3rd',
    3: 'Privacy And Anonymity',
    3_1: 'privacy 2nd',
    3_1_1: 'privacy 3rd',
    4: 'Contents You Don\'t Like',
    4_1: 'contents not like 2nd',
    4_1_1: 'contents 3rd',
}

export const helpData = {
    1: {
        1_1: {
            1_1_1: "Unirep Social Identities are private keys that can be generated by anyone at no cost. ...", 
            1_1_2: "About generating a private key...",
            1_1_3: "About storing your private key...",
        }, 
        1_2: {
            1_2_1: "About platform...",
            1_2_2: "About Pages",
        }
    },
    2: {
        2_1: {
            2_1_1: 'manage account content',
        }
    },
    3: {
        3_1: {
            3_1_1: 'privacy content',
        }
    },
    4: {
        4_1: {
            4_1_1: 'contents content',
        }
    }
}

export const learnData = [
    {
        title: 'Epoch',
        content: 'An epoch is a duration of time; In this case, ~7 days',
        image: 'clock.png'
    }, 
    {
        title: 'Epoch Key',
        content: 'Used to post, vote, and comment, every user receives 5 random epoch keys to use for the duration of one epoch.',
        image: 'epoch-key.png'
    },
    {
        title: 'Epoch Key',
        content: 'Used to post, vote, and comment, every user receives 5 random epoch keys to use for the duration of one epoch.',
        image: 'epoch-key.png'
    },
    {
        title: 'Test',
        content: 'Test something----------------------------------------------------------------------------------------------------------------',
        image: 'arrow-up.png'
    },
]